### ISSUE TITLE
More homogenous date format

### ISSUE THREAD

**Issue by SuperMayo** [cverluise/SciCit#3]
## Problem
The `when` column is a string that could either be the full date (`%Y-%M-%D`) or simply the year (`%Y`) wich makes analyses complicated because one would need to parse date before.

## Feature request
I see two possible workarounds:

1. Coerce year-only cells to `%Y-01-01` but this would mix precise date with truncated dates
2. Having two columns: `date` and `year` where year-only date are coerced to `NULL` in `date` and to the year in `year` (see example below)

#### Before:
|id| when|
|--|-----|
|1| null |
|2| 1993 |
|3| 1969-05-03 |

#### Solution 1
|id| date |
|--|-----|
|1| null |
|2| 1993-01-01 |
|3| 1969-05-03 |

#### Solution 2
|id| date | year
|--|-----| ----|
|1| null  | null
|2| null | 1993 |
|3| 1969-05-03 | 1969 |

**Comment by cverluise** [comment]
Hey @SuperMayo,

thanks for catching it.

you are right, this is currently a first order limitation and should be fixed asap. 

I like your 2nd option. 👍 

Thanks!

**Comment by SuperMayo** [comment]
I just catched cases where you also have `%Y-%M` so solution 2 should include a third column !

### Reproduce results:
```mysql
SELECT a.npl_publn_id, a.when FROM
`npl-parsing.patcit.beta` a
WHERE npl_publn_id = 27
   OR npl_publn_id = 215
   OR npl_publn_id = 10930
```

**Comment by cverluise** [comment]
Hello, 

we have opted for a simple solution. When the `when` (or `idno`, see #4 ) has a date compatible format, we report the publication year in `year`.

I close the issue. Feel free to re-open it if needed. 

Cheers
